version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - mongo_api-data:/etc/mongodb/
    ports:
      - 27018:27017

  api_node:
    container_name: api_node
    image: julinuzzo/api_node:v2
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=$MONGO_DB
      - PORT=$PORT
    ports:
      - 3000:3000
volumes:
  mongo_api-data:
